#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 24 09:54:14 2017

@author: Kathleen Sellick 214504945
"""

#Question 3:


import numpy as np
from matplotlib import pyplot as plt

def fit(x,npoly,points):
    a=np.zeros([x.size,npoly])
    a[:,0]=1
    for i in range(1,npoly):
        a[:,i]=a[:,i-1]*x
    a=np.matrix(a)
    b=np.matrix(points).transpose()
    lhs=a.transpose()*a
    rhs=a.transpose()*b
    fitp=np.linalg.inv(lhs)*rhs
    p=a*fitp
    return p

n=100
x=np.linspace(0,2*np.pi,n)
y=np.sin(x)
z=np.cos(x)
points_y=y+np.random.randn(n)
points_z=z+np.random.randn(n)
npoly=5

p_y=fit(x,npoly,points_y)
p_z=fit(x,npoly,points_z)

plt.plot(x,points_y,"x",label="sine")
plt.plot(x,p_y,"o",label="Fit")
plt.legend()
plt.show()

plt.plot(x,points_z,"x",label="cosine")
plt.plot(x,p_z,"o",label="Fit")
plt.legend()
plt.show()

